from tqdm import tqdm
import torch
from src.checkpointing import load_checkpoint, save_checkpoint
from src.evals import calc_loss_batch, calc_loss_loader, evaluate_model, generate_and_print_sample

def train_modelV0(model, optimizer, criterion, train_loader, val_loader, epochs, 
                start_context, num_batches_to_eval, eval_freq, max_new_tokens, device,
                checkpoint_path, tokenizer, context_length):
    """
    Trains the given model using the given optimizer and criterion for the given number of epochs.
    Evaluates the model after each epoch and prints a sample text generated by the model. 

    Args:
        model (nn.Module): A neural network model
        optimizer (torch.optim.Optimizer): The optimizer used for training
        criterion : the cost function used to calculate the loss
        train_loader (DataLoader): A PyTorch DataLoader object containing the training dataset
        val_loader (DataLoader): A PyTorch DataLoader object containing the validation dataset
        epochs (int): The number of epochs to train the model for
        start_context (str): The initial context to generate text from
        num_batches_to_eval (int): The number of batches to evaluate the model on after each epoch
        eval_freq (int): The frequency of evaluation (in global steps)
        max_new_tokens (int): The maximum number of new tokens to generate
        device (torch.device): The device to run the model on
        checkpoint_path (Path): The path to the checkpoint directory to save and load checkpoints from
        tokenizer : the tokenizer used to encode and decode text
        context_length (int): The length of the context to use for generating text
    
    Returns: 
        train_loss (list): A list of training loss values for each epoch
        train_perplexity (list): A list of training perplexity values for each epoch
        val_loss (list): A list of validation loss values for each epoch
        val_perplexity (list): A list of validation perplexity values for each epoch
        tokens_seen (list): A list of the number of tokens seen by the model after each epoch
    """
    # first check if there is a latest checkpoint and if so load it and resume training from there
    latest_checkpoint_path = checkpoint_path / 'latest_model.pt'

    # first initialize all the variables to be used in the training loop
    train_losses, val_losses, train_ppls, val_ppls, all_tokens_seen = [], [], [], [], []
    tokens_seen, global_step, epoch = 0, -1, 0
    best_val_loss = float('inf')        # initialize this to keep track of the best validation loss seen so far

    # now we check if the latest checkpoint exists and if so load it and resume training from there
    if latest_checkpoint_path.exists():
        print(f"Found latest checkpoint at {latest_checkpoint_path}, loading from the checkpoint...")

        model, optimizer, epoch, global_step, tokens_seen,\
        train_losses, train_ppls, val_losses, val_ppls, all_tokens_seen,\
        best_val_loss = load_checkpoint(latest_checkpoint_path, model, optimizer, device)

        print(f"Resuming training from checkpoint at epoch {epoch+1},\n"
              f"global step {global_step},\n"
              f"tokens seen {tokens_seen:,},\n"
              f"best validation loss {best_val_loss:.4f}")
    else:
        print(f"No latest checkpoint found at {latest_checkpoint_path}, starting training from scratch...")

    for epoch in range(epoch, epochs):      
        model.train()

        # next up we add a progress bar to the training loop to show the progress of the training
        progress_bar = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{epochs}]", unit="batch", dynamic_ncols=True)
        # we make dynamic columns because we will be printing out the metrics next to the loading once we get them
        for input_batch, target_batch in progress_bar:
            optimizer.zero_grad()

            loss = calc_loss_batch(model, input_batch, target_batch, device, criterion)

            loss.backward()

            optimizer.step()
            tokens_seen += input_batch.numel()
            global_step += 1    # an optimizer step

            if (global_step % eval_freq == 0):
                train_loss, train_ppl, val_loss, val_ppl = evaluate_model(model, train_loader, val_loader, device,
                                                                            criterion, num_batches_to_eval)

                train_losses.append(train_loss)
                train_ppls.append(train_ppl)
                val_losses.append(val_loss)
                val_ppls.append(val_ppl)
                all_tokens_seen.append(tokens_seen)

                progress_bar.set_postfix({
                    "Step": f"{global_step}",
                    "Train Loss": f"{train_loss:.4f}",
                    "Train PPL": f"{train_ppl:.4f}",
                    "Val Loss": f"{val_loss:.4f}",
                    "Val PPL": f"{val_ppl:.4f}"
                })
                
                # moreover since the training will take a long time 
                # Save a checkpoint after each evaluation so training can be resumed
                # if the run is interrupted.
                # if the best_val_loss is updated make sure to also update the best model checkpoint
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    save_checkpoint(model, optimizer, epoch, global_step, tokens_seen, train_losses, train_ppls, val_losses, val_ppls, all_tokens_seen,
                                    checkpoint_path, best_val_loss, name='best_model')
                
                save_checkpoint(model, optimizer, epoch, global_step, tokens_seen, train_losses, train_ppls, val_losses, val_ppls, all_tokens_seen,
                                checkpoint_path, best_val_loss, name='latest_model')
                

                

        generate_and_print_sample(model, tokenizer, device, start_context, max_new_tokens, context_length)


        # save yet another one at the very end 
        save_checkpoint(model, optimizer, epoch, global_step, tokens_seen, train_losses, train_ppls, val_losses, val_ppls, all_tokens_seen,
                checkpoint_path, best_val_loss, name='latest_model')

    return train_losses, train_ppls, val_losses, val_ppls, all_tokens_seen